"""Add user profile fields (nullable)

Revision ID: 382d86715952
Revises: a934093167b8
Create Date: 2025-09-04 17:56:27.850349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382d86715952'
down_revision = 'a934093167b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('area')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
